PLATFORM-7866: Fixed calls to private property, doc updated
Wikia/ParserPower pull request #3
Opened 2023-03-09 12:37 UTC by wera-trollcode

### MW 1.39 extension compatibility upgrade
- Replaced call to private property mStripState with getStripState() method
- Shell script for running php code sniffer in docker added
- Docs updated

2023-03-09 15:00 UTC, mszabo-wikia requested changes
We don't have access to `hydrawiki/hydrawiki-codesniffer"` in packagist, making it a liability. We should either remove it or switch to the MW codesniffer.

2023-03-10 09:41 UTC, wera-trollcode commented
@mszabo-wikia then since our repository is public I propose:

# Cut-out REL1_37 from current master (before any code changes) for backwards compatibility if somebody uses this repo on old wikis.
# Create new branch from PLATFORM-7866-mw_1_39-upgrade that will contain mediawiki code-sniffer and code reformatted according to that convention. So we can distinguish real-mw-upgrade changes from code-styling changes.

2023-03-10 11:38 UTC, wera-trollcode commented
@mszabo-wikia all work was done:
REL1_37 was cut from current master
Reformat pull request to this branch is here https://github.com/Wikia/ParserPower/pull/4

2023-03-10 12:41 UTC, mszabo-wikia approved these changes

2023-03-10 12:41 UTC, merged